#!/bin/bash

clear
echo -e "#======================================#"
echo -e "#      Premium Script By Noob96        #"
echo -e "#--------------------------------------#"
echo -e "#            OS Support                #"
echo -e "#         * Debian   9-10              #"
echo -e "#         * Ubuntu  18-20              #"
echo -e "#--------------------------------------#"
echo -e "#           Mod By Noob96              #"
echo -e "#         Thanks To @whytzy96          #"
echo -e "#                                      #"
echo -e "#       Berbagi Config Internet        #"
echo -e "#                                      #"
echo -e "#======================================#"
echo -e "#      Whatsapp : +60169039150         #"
echo -e "#    Telegram : t.me/PrinceNewbie      #"
echo -e "#    Thanks for using this script      #"
echo -e "#======================================#"
