#!/bin/bash
#Script Mod by Prince AKA syapik96
figlet -cf slant "Welcome" | lolcat
figlet -cf slant "Free AutoScript " | lolcat
echo -e "    #====================================================================#" | lolcat
echo -e "    #                  Premium Script By PrinceNewbie                    #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #         ░█▀▀▀█ ░█▄─░█ ░█▀▀▀ 　 ░█▀▀█ ▀█▀ ░█▀▀▀ ░█▀▀█ ░█▀▀▀         #" | lolcat
echo -e "    #         ░█──░█ ░█░█░█ ░█▀▀▀ 　 ░█▄▄█ ░█─ ░█▀▀▀ ░█─── ░█▀▀▀         #" | lolcat
echo -e "    #         ░█▄▄▄█ ░█──▀█ ░█▄▄▄ 　 ░█─── ▄█▄ ░█▄▄▄ ░█▄▄█ ░█▄▄▄         #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #                        - Modded By : PrinceNewbie                  #" | lolcat
echo -e "    #          │▒│  /▒/      - Thanks To : syapik96                      #" | lolcat
echo -e "    #          │▒│ /▒/       - Whatsapp  : *********                     #" | lolcat
echo -e "    #          │▒|/▒/┬─┐     - Telegram  : t.me/PrinceNewbie             #" | lolcat
echo -e "    #          │▒│▒|▒│▒│     - For those who use this script,            #" | lolcat
echo -e "    #         ┌┴─┴─┐-┘─┘       this script is still under development    #" | lolcat
echo -e "    #         │▒┌──┘▒▒▒│     - Thanks for who using this script          #" | lolcat
echo -e "    #         └┐▒▒▒▒▒▒┌┘     - To EnterMenuList = 'menu'                 #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #====================================================================#" | lolcat
echo -e " "
echo -e "                             \e[1;32mPowered By Syapik96\e[0m"
echo -e "                       \e[1;32m\e[1;32mCOPYRIGHT © 2022 Prince Newbie\e[0m"
echo -e "                \e[1;32mPrivacy Policy Terms & Conditions Disclaimer\e[0m"
